// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Gamer struct {
	ID        int32
	FirstName string
	LastName  string
}

type Todo struct {
	ID     int32
	UserID int32
	Task   string
	Done   bool
}
