// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Gamer struct {
	ID        int32  `db:"id" json:"id"`
	FirstName string `db:"first_name" json:"first_name"`
	LastName  string `db:"last_name" json:"last_name"`
}

type Todo struct {
	ID     int32  `db:"id" json:"id"`
	UserID int32  `db:"user_id" json:"user_id"`
	Task   string `db:"task" json:"task"`
	Done   bool   `db:"done" json:"done"`
}
